% This is an autogenerated sample test for rockPaperScissors
classdef rockPaperScissorsTest < matlab.unittest.TestCase
    methods (Test)
        function testRockPaperScissors(testCase)
            % Specify the inputs
            p1c = "paper";
            p2c = "scissors";

            % Exercise the code
            actualOutput_gameResult = rockPaperScissors(p1c,p2c)

            % Specify the expected outputs
            expectedOutput_gameResult = "Player 2 wins";

            % Verify the result
            testCase.verifyEqual(actualOutput_gameResult, expectedOutput_gameResult);
        end
    end
end