% This test file was generated by Copilot. Validate generated output before use.
classdef TestRockPaperScissors < matlab.unittest.TestCase
    methods(Test)
        function testTieCases(testCase)
            % Verify that identical choices return "Tie"
            testCase.verifyEqual(rockPaperScissors("rock","rock"), "Tie");
            testCase.verifyEqual(rockPaperScissors("paper","paper"), "Tie");
            testCase.verifyEqual(rockPaperScissors("scissors","scissors"), "Tie");
        end

        function testPlayer1WinsCases(testCase)
            % Verify all combinations where player 1 should win
            testCase.verifyEqual(rockPaperScissors("rock","scissors"), "Player 1 wins");
            testCase.verifyEqual(rockPaperScissors("scissors","paper"), "Player 1 wins");
            testCase.verifyEqual(rockPaperScissors("paper","rock"), "Player 1 wins");
        end

        function testPlayer2WinsCases(testCase)
            % Verify all combinations where player 2 should win
            testCase.verifyEqual(rockPaperScissors("scissors","rock"), "Player 2 wins");
            testCase.verifyEqual(rockPaperScissors("paper","scissors"), "Player 2 wins");
            testCase.verifyEqual(rockPaperScissors("rock","paper"), "Player 2 wins");
        end

        function testCaseInsensitivity(testCase)
            % Verify function accepts different capitalization due to string inputs
            testCase.verifyEqual(rockPaperScissors("Rock","SCISSORS"), "Player 1 wins");
            testCase.verifyEqual(rockPaperScissors("PaPeR","rock"), "Player 1 wins");
        end

        function testInvalidInputTypeThrows(testCase)
            % Verify that invalid inputs (not members) cause argument validation error
            testCase.verifyError(@() rockPaperScissors("lizard","spock"), 'MATLAB:validators:mustBeMemberFailed');
            testCase.verifyError(@() rockPaperScissors("rock",42), 'MATLAB:argschk:wrongtype'); %#ok<GTARG>
        end
    end
end